// <auto-generated />
using System;
using CarRentalBackend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarRentalBackend.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Avaialblity")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<float>("RentalPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avaialblity = true,
                            Description = "The Mahindra Thar is a compact, four-wheel drive, off-road SUV manufactured by Indian automaker Mahindra and Mahindra Ltd.",
                            Maker = " Corman",
                            Model = "BMW",
                            Rating = 5,
                            RentalPrice = 100f
                        },
                        new
                        {
                            Id = 2,
                            Avaialblity = true,
                            Description = "Renowned for its clarity and depth, this book provides an extensive exploration of algorithms and their applications. From sorting and searching algorithms to graph algorithms and data structures, it offers a wealth of knowledge supported by insightful explanations and practical examples.",
                            Maker = " Corman",
                            Model = "Cargio",
                            Rating = 5,
                            RentalPrice = 100f
                        },
                        new
                        {
                            Id = 3,
                            Avaialblity = true,
                            Description = "The Hyundai Creta, also known as Hyundai ix25 in China, is a subcompact crossover SUV produced by Hyundai since 2014 mainly for emerging markets, particularly BRICS. It is positioned above the Venue and below the Tucson in Hyundai's SUV line-up. ",
                            Maker = "Robert Sedgewick & Kevin Wayne",
                            Model = "Hyundai Creta",
                            Rating = 4,
                            RentalPrice = 200f
                        },
                        new
                        {
                            Id = 4,
                            Avaialblity = true,
                            Description = "The Suzuki Swift is a supermini car produced by Suzuki. The vehicle is classified as a B-segment marque in the European single market, a segment referred to as a supermini in the British Isles.",
                            Maker = "Steve Skiena",
                            Model = "Maruti Swift",
                            Rating = 5,
                            RentalPrice = 300f
                        },
                        new
                        {
                            Id = 5,
                            Avaialblity = true,
                            Description = "The Tata Punch is a crossover city car manufactured by Tata Motors Cars since 2021. Positioned as the smallest SUV of the brand below the Nexon, the Punch is built on ALFA-ARC platform shared with the Altroz hatchback",
                            Maker = "Adnan Aziz",
                            Model = "Tata Punch",
                            Rating = 3,
                            RentalPrice = 400f
                        },
                        new
                        {
                            Id = 6,
                            Avaialblity = true,
                            Description = "Maruti Suzuki, Tata and Toyota are the 3 most popular car brands. These popular car brands cater to a wide spectrum of budgets and needs, offering a variety o",
                            Maker = "Eric Matthes",
                            Model = "TOYOTA",
                            Rating = 3,
                            RentalPrice = 700f
                        },
                        new
                        {
                            Id = 7,
                            Avaialblity = true,
                            Description = "Maruti Suzuki, Tata and Toyota are the 3 most popular car brands. These popular car brands cater to a wide spectrum of budgets and needs, offering a variety o",
                            Maker = "Eric Matthes",
                            Model = "TOYOTA",
                            Rating = 3,
                            RentalPrice = 700f
                        },
                        new
                        {
                            Id = 8,
                            Avaialblity = false,
                            Description = "Maruti Suzuki, Tata and Toyota are the 3 most popular car brands. These popular car brands cater to a wide spectrum of budgets and needs, offering a variety o",
                            Maker = "Eric Matthes",
                            Model = "TOYOTA",
                            Rating = 2,
                            RentalPrice = 700f
                        },
                        new
                        {
                            Id = 9,
                            Avaialblity = false,
                            Description = "The Mahindra Thar is a compact, four-wheel drive, off-road SUV manufactured by Indian automaker Mahindra and Mahindra Ltd.",
                            Maker = "Paul Barry",
                            Model = "Mahindra Thar",
                            Rating = 2,
                            RentalPrice = 800f
                        },
                        new
                        {
                            Id = 10,
                            Avaialblity = true,
                            Description = "The MG 4 EV comes under the category of Hatchback body type. 0 HelpfulReply.",
                            Maker = "Joshua Bloch",
                            Model = "MG Hector",
                            Rating = 3,
                            RentalPrice = 900f
                        },
                        new
                        {
                            Id = 11,
                            Avaialblity = true,
                            Description = "The MG 4 EV comes under the category of Hatchback body type. 0 HelpfulReply.",
                            Maker = "Joshua Bloch",
                            Model = "MG Hector",
                            Rating = 4,
                            RentalPrice = 900f
                        },
                        new
                        {
                            Id = 12,
                            Avaialblity = true,
                            Description = "Seating Capacity: It is available in 7- and 9-seater layout. Engine and Transmission: The Scorpio Classic is powered by a 2.2-litre diesel engine, derived from the Scorpio N's less powerful diesel version, that makes 132 PS and 300 Nm, and is mated to a 6-speed manual gearbox.",
                            Maker = "James F Kurose and Keith W Ross",
                            Model = "Scropio",
                            Rating = 4,
                            RentalPrice = 1400f
                        },
                        new
                        {
                            Id = 13,
                            Avaialblity = true,
                            Description = "Maruti Suzuki, Tata and Toyota are the 3 most popular car brands. These popular car brands cater to a wide spectrum of budgets and needs, offering ",
                            Maker = "Rich Seifert and James Edwards",
                            Model = "Maruti Suzuki Brezza",
                            Rating = 3,
                            RentalPrice = 1500f
                        },
                        new
                        {
                            Id = 14,
                            Avaialblity = true,
                            Description = "Maruti Suzuki, Tata and Toyota are the 3 most popular car brands. These popular car brands cater to a wide spectrum of budgets and needs, offering .",
                            Maker = "Rich Seifert and James Edwards",
                            Model = "Maruti Suzuki Brezza",
                            Rating = 5,
                            RentalPrice = 1500f
                        });
                });

            modelBuilder.Entity("CarRentalBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgrrementId")
                        .HasColumnType("int");

                    b.Property<bool>("Avaialblity")
                        .HasColumnType("bit");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgrrementId = 0,
                            Avaialblity = false,
                            CarId = 1,
                            Days = 5,
                            Email = "Sai@gmail.com",
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalEndDate = new DateTime(2024, 6, 23, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            RentalStartDate = new DateTime(2024, 6, 19, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            TotalCost = 0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AgrrementId = 0,
                            Avaialblity = false,
                            CarId = 4,
                            Days = 3,
                            Email = "Sai@gmail.com",
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalEndDate = new DateTime(2024, 6, 21, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            RentalStartDate = new DateTime(2024, 6, 19, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            TotalCost = 0m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CarRentalBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 6, 11, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            MobileNumber = "1234567890",
                            Password = "admin1234",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserType = "ADMIN",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 3, 6, 13, 30, 12, 0, DateTimeKind.Unspecified),
                            Email = "sai@gmail.com",
                            FirstName = "sai",
                            LastName = "lakshmi",
                            MobileNumber = "1234567890",
                            Password = "sai1234",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserType = "USER",
                            Username = "sai"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
